### ISSUE TITLE
Some elements get stale when scraping Billetweb

### ISSUE THREAD

**Issue by thomas-bouvier** [trouver-une-fresque/trouver-une-fresque#22]
Some elements may get stale when scraping Billetweb, raising a `StaleElementReferenceException` exception. Specifically, the object [here](https://github.com/trouver-une-fresque/trouver-une-fresque/blob/a32d9154729c3e09ecedac996d840b9bdd11628e/scraper/billetweb.py#L198-L199) causes the issue.

```
Processing event https://www.billetweb.fr/var-83&multi=17309&margin=no_margin&color=99ad23&parent=fresquedelabiodiversite&margin=no_margin&color=99ad23
Traceback (most recent call last):
  File "/home/tbouvier/Dev/trouver-une-fresque/scrape.py", line 27, in <module>
    df1 = main_scraper(headless=args.headless)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tbouvier/Dev/trouver-une-fresque/scraper/main.py", line 26, in main
    records += get_billetweb_data(service=service, options=options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tbouvier/Dev/trouver-une-fresque/scraper/billetweb.py", line 199, in get_billetweb_data
    if "Step 2 : Basket" in step.text:
                            ^^^^^^^^^
  File "/home/tbouvier/Dev/trouver-une-fresque/.venv/lib64/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 90, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tbouvier/Dev/trouver-une-fresque/.venv/lib64/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tbouvier/Dev/trouver-une-fresque/.venv/lib64/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "/home/tbouvier/Dev/trouver-une-fresque/.venv/lib64/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element with the reference 3bdc9ccd-ae61-47e8-8cd4-f524762cba41 is stale; either its node document is not the active document, or it is no longer connected to the DOM; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5
StaleElementReferenceError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:676:5
getKnownElement@chrome://remote/content/marionette/json.sys.mjs:401:11
deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:259:20
cloneObject@chrome://remote/content/marionette/json.sys.mjs:59:24
deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:289:16
json.deserialize@chrome://remote/content/marionette/json.sys.mjs:293:10
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:72:30
```

**Comment by csauge** [comment]
I think you can close this ticket now ?

**Comment by thomas-bouvier** [comment]
Closing, will reopen after the next round if needed
